{% set name = "biobb" %}
{% set version = "1.0.1" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "11a6ac087a0d2d4210049d4f90f36173292b48a19ad31a9ddb7b05dd95973ef8" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  noarch: python

requirements:
  host:
    - python ==3.6.*
    - setuptools
    - m2r
    - biobb_common ==1.1.6
    - biobb_io ==1.1.6
    - biobb_model ==1.1.9
    - biobb_md ==1.1.6
    - biobb_analysis ==1.0.3
    - biobb_chemistry ==1.0.6
    - biobb_pmx ==1.0.0
  run:
    - python ==3.6.*
    - m2r
    - biobb_common ==1.1.6
    - biobb_io ==1.1.6
    - biobb_model ==1.1.9
    - biobb_md ==1.1.6
    - biobb_analysis ==1.0.3
    - biobb_chemistry ==1.0.6
    - biobb_pmx ==1.0.0

test:
  imports:
    - biobb_common
    - biobb_io
    - biobb_model
    - biobb_md
    - biobb_analysis
    - biobb_chemistry
    - biobb_pmx

about:
  home: https://github.com/bioexcel/biobb
  license: Apache Software License
  license_family: APACHE
  license_file: ''
  summary: Biobb module collection.
  description: "# Biobb\n\n### Introduction\nBiobb (BioExcel building blocks) packages are Python building blocks that\ncreate new layer of compatibility and interoperability over popular\nbioinformatics\
    \ tools.\nThe latest documentation of our biobb collections can be found in our readthedocs sites:\n- [biobb_io](http://biobb_io.readthedocs.io/en/latest/) [\\[GitHub\\]](https://github.com/bioexcel/biobb_io):\
    \ Biobb collection to fetch data to be consumed by the rest of the Biobbs.\n- [biobb_model](http://biobb_model.readthedocs.io/en/latest/) [\\[GitHub\\]](https://github.com/bioexcel/biobb_model): Biobb\
    \ collection to check and model 3d protein structures.\n- [biobb_md](http://biobb_md.readthedocs.io/en/latest/) [\\[GitHub\\]](https://github.com/bioexcel/biobb_md): Biobb collection to perform molecular\
    \ dynamics simulations.\n- [biobb_analysis](http://biobb_analysis.readthedocs.io/en/latest/) [\\[GitHub\\]](https://github.com/bioexcel/biobb_analysis): Biobb collection to perform analysis over molecular\
    \ dynamics simulations.\n- [biobb_wf_mutations](http://biobb_wf_mutations.readthedocs.io/en/latest/) [\\[GitHub\\]](https://github.com/bioexcel/biobb_wf_mutations): Workflow performing molecular dynamics\
    \ simulations of protein mutants.\n- [biobb_adapters](http://biobb_adapters.readthedocs.io/en/latest/) [\\[GitHub\\]](https://github.com/bioexcel/biobb_adapters): Biobb collection to use the building\
    \ blocks with several workflow managers.\n- [biobb_common](http://biobb_common.readthedocs.io/en/latest/) [\\[GitHub\\]](https://github.com/bioexcel/biobb_common): Common tools to use the rest of the\
    \ Biobb building blocks.\n- [biobb_template](http://biobb_template.readthedocs.io/en/latest/) [\\[GitHub\\]](https://github.com/bioexcel/biobb_template): Boilerplate code and template examples to create\
    \ your own Biobbs.\n\n### Version\nv1.0.1 May 2019 Release\n\n### Copyright & Licensing\nThis software has been developed in the MMB group (http://mmb.irbbarcelona.org) at the\nBSC (http://www.bsc.es/)\
    \ & IRB (https://www.irbbarcelona.org/) for the European BioExcel (http://bioexcel.eu/), funded by the European Commission\n(EU H2020 [675728](http://cordis.europa.eu/projects/675728)).\n\n* (c) 2015-2019\
    \ [Barcelona Supercomputing Center](https://www.bsc.es/)\n* (c) 2015-2019 [Institute for Research in Biomedicine](https://www.irbbarcelona.org/)\n\nLicensed under the\n[Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0),\
    \ see the file\n[LICENSE](LICENSE) for details.\n\n![](https://bioexcel.eu/wp-content/uploads/2015/12/Bioexcell_logo_1080px_transp.png \"Bioexcel\")\n\n\n"
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
