{% set version = "0.9.5" %}
package:
  name: goatools
  version: '{{version}}'

source:
  url: https://pypi.io/packages/source/g/goatools/goatools-{{version}}.tar.gz
  sha256: 30592dd2dfbfa1ee697658242502cb4d9453d081b8c16817ecacdfc725f4c1d9

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - python-wget
    - numpy
    - scipy
    - xlsxwriter
    - statsmodels
    # xlrd only used in excluded test_data
    # - xlrd
    - pygraphviz
    - pydot

test:
  commands:
    - find_enrichment.py -h
    - map_to_slim.py -h
    - plot_go_term.py -h
  imports:
    - goatools
    - goatools.obo_parser
    - goatools.go_enrichment
    - goatools.associations

about:
  home: 'https://github.com/tanghaibao/goatools'
  summary: 'Python scripts to find enrichment of GO terms'
  license: BSD-2-Clause
  license_family: BSD

extra:
  identifiers:
    - doi:10.5281/zenodo.31628
